import {
  SystemGraph,
  DiagramNode,
  DiagramLink,
  NodeShape,
  DiagramLayer,
  NodeSeverity,
} from "@/types/diagram";

/**
 * Parses a Mermaid flowchart string into a SystemGraph JSON structure.
 * This parser specifically targets the "flowchart TD/LR" format generated by the AI.
 */
export function parseMermaidToJSON(mermaidCode: string): SystemGraph {
  const nodes: DiagramNode[] = [];
  const links: DiagramLink[] = [];
  let direction: "TD" | "LR" = "TD";

  // 1. Determine direction
  if (
    mermaidCode.includes("flowchart LR") ||
    mermaidCode.includes("graph LR")
  ) {
    direction = "LR";
  }

  const lines = mermaidCode.split("\n");
  let currentSubgraphId: string | undefined;
  let currentSubgraphTitle: string | undefined;

  for (let line of lines) {
    line = line.trim();
    if (!line || line.startsWith("flowchart") || line.startsWith("graph"))
      continue;

    // 2. Handle Subgraphs
    // Supports: subgraph id["Title"], subgraph id ["Title"], subgraph id
    const subgraphMatch = line.match(/subgraph\s+([\w-]+)\s*(?:\["(.+?)"\])?/i);
    if (subgraphMatch) {
      currentSubgraphId = subgraphMatch[1];
      currentSubgraphTitle = subgraphMatch[2] || subgraphMatch[1];
      continue;
    }
    if (line === "end") {
      currentSubgraphId = undefined;
      currentSubgraphTitle = undefined;
      continue;
    }

    // 3. Handle Nodes
    // Supports formats: A["Label"], B{"Label"}, C(("Label")), D[("Label")], E(["Label"]), F{{"Label"}}, G[/"Label"/], H[\"Label"\]
    const nodeMatch = line.match(
      /^([\w-]+)\s*(?:\["(.+?)"\]|\{"(.+?)"\}|\(\("(.+?)"\)\)|\[\("(.+?)"\)\]|\(\["(.+?)"\]\)|\{\{"(.+?)"\}\}|\[\/"(.+?)"\/\]|\[\\"(.+?)"\\\])/,
    );
    if (nodeMatch) {
      const [
        full,
        id,
        rectLabel,
        diamondLabel,
        circleLabel,
        cylinderLabel,
        stadiumLabel,
        hexLabel,
        paraLabel1,
        paraLabel2,
      ] = nodeMatch;
      const label =
        rectLabel ||
        diamondLabel ||
        circleLabel ||
        cylinderLabel ||
        stadiumLabel ||
        hexLabel ||
        paraLabel1 ||
        paraLabel2 ||
        id;

      let shape: NodeShape = "rectangle";
      if (diamondLabel) shape = "diamond";
      else if (circleLabel) shape = "circle";
      else if (cylinderLabel) shape = "cylinder";
      else if (stadiumLabel) shape = "stadium";
      else if (hexLabel) shape = "hexagon";
      else if (paraLabel1 || paraLabel2) shape = "parallelogram";

      // Deduplicate nodes
      if (!nodes.find((n) => n.id === id)) {
        nodes.push({
          id,
          label,
          type: inferTypeFromLabel(label),
          shape,
          layer: inferLayerFromContext(label, currentSubgraphTitle),
          severity: "Medium", // Will be calculated in the second pass
          subgraphId: currentSubgraphId,
          subgraphTitle: currentSubgraphTitle,
        });
      }
      continue;
    }

    // 4. Handle Links
    // Supports formats: A --> B, A -.-> B, A ==> B, and labeled variants A -- "Label" --> B, A -->|"Label"| B
    const linkMatch = line.match(
      /([\w-]+)\s*(?:(?:--|-\.-|==)\s*"(.+?)"\s*(?:-->|-\.->|==>)|(?:-->|-\.->|==>)\|"(.+?)"\||(-->|-\.->|==>))\s*([\w-]+)/,
    );
    if (linkMatch) {
      const [full, source, label1, label2, linkType, target] = linkMatch;
      let type: "sync" | "async" | "fallback" = "sync";
      if (full.includes("-.-")) type = "async";
      if (full.includes("==")) type = "fallback";

      links.push({
        source,
        target,
        label: label1 || label2,
        type,
      });

      // Ensure nodes mentioned in links exist (if they weren't defined explicitly)
      [source, target].forEach((nodeId) => {
        if (!nodes.find((n) => n.id === nodeId)) {
          nodes.push({
            id: nodeId,
            label: nodeId,
            type: "Unknown",
            shape: "rectangle",
            layer: "Unknown",
            severity: "Medium",
            subgraphId: currentSubgraphId,
            subgraphTitle: currentSubgraphTitle,
          });
        }
      });
    }
  }

  // 5. Calculate Severity (Second pass based on graph topology)
  nodes.forEach((node) => {
    const incomingConnections = links.filter(
      (l) => l.target === node.id,
    ).length;
    const outgoingConnections = links.filter(
      (l) => l.source === node.id,
    ).length;
    node.severity = calculateNodeSeverity(
      node,
      incomingConnections,
      outgoingConnections,
    );
  });

  return {
    nodes,
    links,
    metadata: {
      generatedAt: new Date().toISOString(),
      version: "1.0.0",
      direction,
    },
  };
}

/**
 * Heuristic to infer the component type from its label.
 */
function inferTypeFromLabel(label: string): string {
  const l = label.toLowerCase();
  if (
    l.includes("db") ||
    l.includes("database") ||
    l.includes("postgresql") ||
    l.includes("redis")
  )
    return "Database";
  if (l.includes("api") || l.includes("gateway") || l.includes("service"))
    return "Service";
  if (
    l.includes("app") ||
    l.includes("ui") ||
    l.includes("client") ||
    l.includes("frontend")
  )
    return "Frontend";
  if (l.includes("queue") || l.includes("kafka") || l.includes("rabbitmq"))
    return "Message Broker";
  return "Component";
}

/**
 * Heuristic to infer the architectural layer.
 */
function inferLayerFromContext(
  label: string,
  subgraphTitle?: string,
): DiagramLayer {
  const context = (label + " " + (subgraphTitle || "")).toLowerCase();
  if (context.includes("infra") || context.includes("cloud"))
    return "Infrastructure";
  if (
    context.includes("db") ||
    context.includes("database") ||
    context.includes("storage")
  )
    return "Database";
  if (
    context.includes("api") ||
    context.includes("server") ||
    context.includes("backend")
  )
    return "API";
  if (
    context.includes("ui") ||
    context.includes("app") ||
    context.includes("frontend")
  )
    return "Frontend";
  if (context.includes("external") || context.includes("auth"))
    return "External";
  return "Unknown";
}

/**
 * Heuristic to calculate the severity/criticality of a node based on its dependencies.
 */
function calculateNodeSeverity(
  node: DiagramNode,
  incomingCount: number,
  outgoingCount: number,
): NodeSeverity {
  if (node.layer === "Database") return "Critical";
  if (node.layer === "Infrastructure") return "High";

  if (incomingCount >= 3) return "Critical";
  if (incomingCount === 2) return "High";
  if (incomingCount === 1 || outgoingCount >= 2) return "Medium";

  return "Low";
}
